#!/bin/bash

theme="$1"

# run functions
make_env() {
 cp "links/colors/3.0/$theme.css" Debug/3.0/gtk.css
 touch Debug/3.0/gtk-widgets.css

 cp "links/colors/3.20/$theme.css" Debug/3.20/gtk.css
 touch Debug/3.20/gtk-widgets.css
}

write_file() {

 tput setaf 3

 if [ -a links/widgets/$1/$2/$theme.css ]; then
  cat links/widgets/$1/$2/$theme.css >> Debug/$1/gtk-widgets.css
 else
  printf "\n[ERROR] File missing in $1/$2: $theme.css "
 fi

 tput setaf 7

}

conditions() {
 # select case & make operations

 case $1 in
  1)
    write_file $2 wildcard;;
  2)
    write_file $2 button
    write_file $2 entry;;
  3)
    write_file $2 combo;;
  4)
    write_file $2 menumenubar;;
  5)
    write_file $2 notebook;;
  6)
    write_file $2 scrollprogress;;
  7)
    write_file $2 headerbarseparator;;
  8)
    write_file $2 spinbutton;;
  9)
    write_file $2 switch;;
  10)
    write_file $2 x-bar
    write_file $2 linkedbuttons;;
  11)
    write_file $2 titlebar;;
   *);;
 esac

}

get_code() {
 start=1
 end=12
 for (( c=$start; c<=$end; c++  ))
 do
  cat "links/common/$1/source/s$c.css" >> "Debug/$1/gtk-widgets.css"

  # Inject code here, depending on stuff
  conditions $c "$1"
  # depending on number, we'll use different stuff
 done
}

get_assets() {

# copy assets
 cp -R links/assets/3.0/$theme/. Debug/3.0
 cp -R links/assets/3.20/$theme/. Debug/3.20/

 case $theme in
  plex)
    cp links/common/3.0/assets-plex.css Debug/3.0/gtk-widgets-assets.css
    cp -a links/common/3.0/apps-all Debug/3.0/apps
    cp -a links/common/3.0/apps-plex/* Debug/3.0/apps

# 3.20
    cp links/common/3.20/assets-plex.css Debug/3.20/gtk-widgets-assets.css
    cp -a links/common/3.20/apps-all Debug/3.20/apps
    ;;
  slate)
    cp links/common/3.0/assets-slate.css Debug/3.0/gtk-widgets-assets.css
    cp -a links/common/3.0/apps-all Debug/3.0/apps
    cp -a links/common/3.0/apps-slate/* Debug/3.0/apps
# 3.20
    cp links/common/3.20/assets-slate.css Debug/3.20/gtk-widgets-assets.css
    cp -a links/common/3.20/apps-all Debug/3.20/apps
    ;;
  whistler)
    cp links/common/3.0/assets-whistler.css Debug/3.0/gtk-widgets-assets.css
    cp -a links/common/3.0/apps-all Debug/3.0/apps
    cp -a links/common/3.0/apps-whistler/* Debug/3.0/apps
# 3.20
    cp links/common/3.20/assets-whistler.css Debug/3.20/gtk-widgets-assets.css
    cp -a links/common/3.20/apps-all Debug/3.20/apps
    cp -a links/common/3.20/apps-whistler/* Debug/3.20/apps
    ;;
  8)
    cp links/common/3.0/assets-8.css Debug/3.0/gtk-widgets-assets.css
    cp -a links/common/3.0/apps-all Debug/3.0/apps

# 3.20
    cp links/common/3.20/assets-all.css Debug/3.20/gtk-widgets-assets.css
    cp -a links/common/3.20/apps-all Debug/3.20/apps
    ;;
  vista)
    ;;
  *)
    cp links/common/3.0/assets-all.css Debug/3.0/gtk-widgets-assets.css
    cp -a links/common/3.0/apps-all Debug/3.0/apps

# 3.20
    cp links/common/3.20/assets-all.css Debug/3.20/gtk-widgets-assets.css
    cp -a links/common/3.20/apps-all Debug/3.20/apps
    ;;
 esac

 # get settings.ini
 cp links/common/3.0/settings.ini Debug/3.0
 cp links/common/3.20/settings.ini Debug/3.20
}

put_thumbs() {
 cp -a "links/thumbnails/$theme.png" Debug/3.0/thumbnail.png
 cp -a "links/thumbnails/$theme.png" Debug/3.20/thumbnail.png
}

make_env
get_code "3.0"
get_code "3.20" # 3.20
get_assets
put_thumbs
