#!/bin/bash

# Modular Theme Compiler
# Version: v0.3
# Script by Christian Medel (elbullazul) <cmedelahumada@gmail.com>
# March 16th, 2017
# License: GPL v3

theme="$1"

write_file() {

 tput setaf 3

 if [ -a links/widgets/$1/$2/$theme.css ]; then
  cat links/widgets/$1/$2/$theme.css >> Debug/$1/gtk-widgets.css
 else
  echo -e "[ERROR] File missing in $1/$2: $theme.css"
 fi

 tput setaf 7

}

inject() {
 source="links/common/$1/tree.css"

 while IFS='' read -r line || [[ -n "$line" ]]; do
  if [[ $line == *! ]]; then
   widget=${line#'!---'}
   widget=${widget%'---!'}
   write_file $1 $widget
  else
   echo "$line" >> "Debug/$1/gtk-widgets.css"
  fi
 done < "$source"
}

get_files() {

 # include assets, assets CSS code, colors and apps
 location="$PWD"

 cd links/static/$1/$theme
 cp -RL * "$location/Debug/$1"
 cd "$location"

}

inject "3.0"
inject "3.20" #3.20
get_files '3.0'
get_files '3.20' #3.20
